spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smabro_app_db?serverTimezone=JST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialization-mode: always
    sql-script-encoding: utf-8
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath*:/sql/*/*.xml

# 開発を効率化するためにjsから読み取れるようにhttp-only: falseとする
server.servlet:
  session:
    cookie:
      http-only: false
      secure: false